import os
import sys
import shutil
import subprocess
from pathlib import Path

try:
    from dotenv import load_dotenv  # type: ignore
except Exception:  # pragma: no cover
    load_dotenv = None  # type: ignore

from yt_dlp.cookies import extract_cookies_from_browser  # type: ignore
import http.cookiejar as cookiejar
import qrcode


def find_chrome() -> str | None:
    candidates = [
        "google-chrome",
        "google-chrome-stable",
        "chromium",
        "chromium-browser",
        "brave-browser",
        "chrome",
    ]
    for c in candidates:
        path = shutil.which(c)
        if path:
            return path
    return None


def update_env_cookies(path: str) -> None:
    env_path = Path(".env")
    lines = []
    if env_path.exists():
        lines = env_path.read_text(encoding="utf-8").splitlines()
    wrote = False
    for i, line in enumerate(lines):
        if line.startswith("YTDLP_COOKIES_FILE="):
            lines[i] = f"YTDLP_COOKIES_FILE={path}"
            wrote = True
            break
    if not wrote:
        lines.append(f"YTDLP_COOKIES_FILE={path}")
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Updated .env with YTDLP_COOKIES_FILE={path}")


def save_cookies_netscape(cj: cookiejar.CookieJar, filename: str) -> None:
    p = Path(filename)
    p.parent.mkdir(parents=True, exist_ok=True)
    with p.open("w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by tools/google_auth_flow.py\n\n")
        for c in cj:
            domain = c.domain or ""
            include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.path or "/"
            secure = "TRUE" if getattr(c, "secure", False) else "FALSE"
            expires = str(int(c.expires)) if getattr(c, "expires", None) else "0"
            name = c.name or ""
            value = c.value or ""
            f.write("\t".join([domain, include_subdomains, path, secure, expires, name, value]) + "\n")


def main() -> int:
    if load_dotenv:
        try:
            load_dotenv()
        except Exception:
            pass

    chrome = find_chrome()
    if not chrome:
        print("[!] Chrome/Chromium not found. Install Chrome/Chromium or use tools.ytdlp_auth.")
        return 2

    workdir = Path(os.getcwd())
    profile_dir = workdir / ".google-auth-profile"
    profile_dir.mkdir(parents=True, exist_ok=True)

    login_url = "https://accounts.google.com/ServiceLogin?continue=https://www.youtube.com"
    cmd = [
        chrome,
        f"--user-data-dir={str(profile_dir)}",
        "--no-default-browser-check",
        "--no-first-run",
        login_url,
    ]
    print("Launching Chrome. Please log into your Google account in the opened window.")
    print("Alternatively, open this QR on your phone to get to the same page:")
    qr = qrcode.QRCode(border=1)
    qr.add_data(login_url)
    qr.make(fit=True)
    mat = qr.get_matrix()
    black = "\u2588\u2588"; white = "  "
    for row in mat:
        print("".join(black if cell else white for cell in row))
    print("After you have logged in inside the Chrome window, return here and press Enter to capture cookies…")

    try:
        proc = subprocess.Popen(cmd)  # noqa: S603,S607
    except Exception as e:
        print(f"[!] Failed to launch Chrome: {e}")
        return 3

    try:
        input("Press Enter to capture cookies… ")
    finally:
        # Try to terminate browser (optional)
        try:
            proc.terminate()
        except Exception:
            pass

    # Extract cookies from the temporary profile
    try:
        cookies = extract_cookies_from_browser("chrome", profile=str(profile_dir))
    except Exception as e:
        print(f"[!] Failed to extract cookies from browser: {e}")
        return 4

    out = workdir / "cookies.txt"
    save_cookies_netscape(cookies, str(out))
    print(f"Saved cookies to {out}")
    update_env_cookies(str(out))
    print("Done. Restart your bot to apply cookies.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
